### ISSUE TITLE
Corda 4.1. State is not available in sender's Party. 

### ISSUE THREAD

**Issue by prateektiwari7** [corda/corda#5441]
Hello Corda Team,

I don't know whether it is a bug or I am missing something.But I am not getting any state in the sender section. 

Here is the code. 

**NameState.kt**

```
`@BelongsToContract(NameContract::class)
data class NameState(val name: String,
                     val lastname : String,
                     val party: Party,
                     val linearId: UniqueIdentifier) : ContractState {

    override val participants: List<AbstractParty> = listOf(party);
    //To change initializer of created properties use File | Settings | File Templates.

}`
```

**NameContract.kt** 

```
class NameContract : Contract {
      companion object{
        const val ID = "com.template.contracts.NameContract"
    }

    override fun verify(tx: LedgerTransaction) {
        val command = tx.commands.requireSingleCommand<Commands.Create>()
        requireThat {
            "No Inputs should be empty" using (tx.inputs.isEmpty())
            "Only one output state should be created" using (tx.outputs.size ==1)
            val out = tx.outputsOfType<NameState>().single()
            "Name cant be 7 character long " using (out.name.length != 7)
            "Name cant be Same as Admin 'Prateek' " using (!(out.name.equals("Prateek")))


        }
    }

    interface Commands : CommandData {
        class Create : NameContract.Commands;
    }
}
```

**NameFlow.kt**

```
@InitiatingFlow
@StartableByRPC
class NameFlow constructor( var name:String,
                            var lastname : String, var party: Party): FlowLogic<SignedTransaction>() {

    @Suspendable
    override fun call() : SignedTransaction {

        val notary = serviceHub.networkMapCache.notaryIdentities.first()
        val command = Command(NameContract.Commands.Create(), listOf(party).map { it.owningKey })

        val namestate = NameState(name,lastname,party, UniqueIdentifier())

        val txBuilder = TransactionBuilder(notary)
                .addOutputState(namestate, NameContract.ID)
                .addCommand(command)

        txBuilder.verify(serviceHub)
        val tx = serviceHub.signInitialTransaction(txBuilder)

        val sessions = (namestate.participants).map { initiateFlow(it as Party) }
        val stx = subFlow(CollectSignaturesFlow(tx, sessions))
        return subFlow(FinalityFlow(stx, sessions))
    }

}

@InitiatedBy(NameFlow::class)
class NameResponder(val counterpartySession: FlowSession) : FlowLogic<SignedTransaction>() {
    @Suspendable
    override fun call() : SignedTransaction {
        val signedTransactionFlow = object : SignTransactionFlow(counterpartySession) {
            override fun checkTransaction(stx: SignedTransaction) = requireThat {
                val output = stx.tx.outputs.single().data

            }
        }
        val txWeJustSignedId = subFlow(signedTransactionFlow)
        return subFlow(ReceiveFinalityFlow(counterpartySession, txWeJustSignedId.id))
    }
}
```

**In the command prompt of PartyB:-** 
`Fri Sep 06 18:34:41 IST 2019>>> flow start NameFlow name: POIU, lastname: opi, party: PartyA
`
**And The State returns**

```
Fri Sep 06 18:36:02 IST 2019>>> run vaultQuery contractStateType: com.template.states.NameState 
states: []
statesMetadata: []
totalStatesAvailable: -1
stateTypes: "UNCONSUMED"
otherResults: [] 
```

**While in command prompt of PartyA**

```
Fri Sep 06 18:34:26 IST 2019>>> run vaultQuery contractStateType: com.template.states.NameState
states:
- state:
    data: !<com.template.states.NameState>
      name: "POIU"
      lastname: "opi"
      party: "O=PartyA, L=London, C=GB"
      linearId:
        externalId: null
        id: "a386b8a2-c3cc-4071-adb4-0a8921e34d1f"
    contract: "com.template.contracts.NameContract"
    notary: "O=Notary, L=London, C=GB"
    encumbrance: null
    constraint: !<net.corda.core.contracts.SignatureAttachmentConstraint>
      key: "aSq9DsNNvGhYxYyqA9wd2eduEAZ5AXWgJTbTEw3G5d2maAq8vtLE4kZHgCs5jcB1N31cx1hpsLeqG2ngSysVHqcXhbNts6SkRWDaV7xNcr6MtcbufGUchxredBb6"
  ref:
    txhash: "1545DF3AD56BEE4819DB685D57F628E288B1F9B150C10B09486E2CECF967C391"
    index: 0
statesMetadata:
- ref:
    txhash: "1545DF3AD56BEE4819DB685D57F628E288B1F9B150C10B09486E2CECF967C391"
    index: 0
  contractStateClassName: "com.template.states.NameState"
  recordedTime: "2019-09-06T13:05:23.042Z"
  consumedTime: null
  status: "UNCONSUMED"
  notary: "O=Notary, L=London, C=GB"
  lockId: null
  lockUpdateTime: null
  relevancyStatus: "RELEVANT"
  constraintInfo:
    constraint:
      key: "aSq9DsNNvGhYxYyqA9wd2eduEAZ5AXWgJTbTEw3G5d2maAq8vtLE4kZHgCs5jcB1N31cx1hpsLeqG2ngSysVHqcXhbNts6SkRWDaV7xNcr6MtcbufGUchxredBb6"
totalStatesAvailable: -1
stateTypes: "UNCONSUMED"
otherResults: []

```

**Why the state of partyB is empty??** 

While the older version of corda 4.0 has state of partyB
